version: '3.8'

networks:
  ptero-network:
    driver: bridge

services:
  database:
    image: mariadb:10.5
    command: --allow-no-password
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia_root
      - MYSQL_DATABASE=panel
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=rahasia_ptero
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - ptero-network
    # --- METODE UTAMA (HEALTHCHECK) ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prahasia_root"]
      timeout: 5s
      retries: 10
      interval: 5s

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    ports:
      - "80:80"
    environment:
      - APP_URL=http://localhost
      - APP_ENV=production
      - APP_ENVIRONMENT_ONLY=false
      - APP_KEY=base64:d3B6NWhwYm9wY2NteXN0ZXJ5a2V5MTIzNDU2Nzg5MDA=
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=panel
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=rahasia_ptero
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    volumes:
      - ./data/panel:/app/var/
    networks:
      - ptero-network
    depends_on:
      database:
        condition: service_healthy # Panel baru akan jalan setelah database berstatus HEALTHY

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    ports:
      - "8080:8080"
      - "2022:2022"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/wings:/var/lib/pterodactyl
    networks:
      - ptero-network
      
