version: '3.8'
services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    ports:
      - "80:80"
    environment:
      - APP_URL=http://localhost
      - DB_HOST=database
      - DB_PASSWORD=rahasia
    volumes:
      - ./data/panel:/app/var/
  
  database:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=panel
    volumes:
      - ./data/db:/var/lib/mysql

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    ports:
      - "8080:8080"
      - "2022:2022"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/wings:/var/lib/pterodactyl
      
